docker-proxy :
 image: nginx:alpine
 container_name: docker-proxy
 hostname: docker-proxy
 restart: always
 ports:
  - "80:80"
  - "443:443"
 volumes:
  - "/opt/docker-proxy/nginx.conf:/etc/nginx/nginx.conf:ro"
  - "/opt/docker-proxy/vhosts:/etc/nginx/vhosts:ro"
  - "/opt/docker-proxy/www:/var/www:ro"